/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/world.glb -o src/components/WorldModelGLTF.jsx

수동 수정: 경로 /models/world.glb, Mill_Wing(제어문자 키), Carbon_Land.001 별칭, 그림자 traverse.
주의: 메시가 GLB nodes 의 geometry 만 빌려 쓰는 형태라, WorldModel 의 nodes.Gear_* 회전은
이 JSX 로 그린 메시와 Object3D 가 다를 수 있습니다. 맵+애니메이션은 기존 WorldModel(primitive+clone) 유지 권장.
*/

import React, { memo, useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const WORLD_GLB = '/models/world.glb'

export const WorldModelGLTF = memo(function WorldModelGLTF(props) {
  const { nodes, materials } = useGLTF(WORLD_GLB)
  const rootRef = useRef(null)

  useLayoutEffect(() => {
    rootRef.current?.traverse((o) => {
      if (o.isMesh) {
        o.castShadow = true
        o.receiveShadow = true
      }
    })
  }, [])

  return (
    <group ref={rootRef} {...props} dispose={null}>
      <group position={[100, -84.92, 0]}>
        <mesh geometry={nodes.Propeller.geometry} material={materials.All_Material} position={[-79.357, 192.003, 9.787]} rotation={[2.843, 0.939, -1.328]} />
        <mesh geometry={nodes.Wings.geometry} material={materials.All_Material} position={[-79.22, 191.284, 3.295]} rotation={[2.843, 0.939, -1.328]} />
      </group>
      <mesh geometry={nodes.Air_Quality.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Institution_Promtion_Zone.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Carbon_Neutrality_Zone.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Water_Quality_Zone.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Measurement_Analysis_Zone.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Foregin_Pavilion_Zone.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Center.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Water_all.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Water_Quality_Land.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Foreign_Land.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Institution_Land.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Measurement_Land.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Air_Land.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Water_building.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.Moutain_01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Moutain_02.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Moutain_03.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Gear_A.geometry} material={materials.All_Material} position={[-52.472, 24.189, -58.483]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Gear_G.geometry} material={materials.All_Material} position={[-56.087, 12.157, -55.951]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Gear_D.geometry} material={materials.All_Material} position={[-42.115, 12.334, -65.982]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Gear_B.geometry} material={materials.All_Material} position={[-48.946, 12.823, -61.323]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Gear_C.geometry} material={materials.All_Material} position={[-46.117, 18.465, -63.304]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Gear_E.geometry} material={materials.All_Material} position={[-37.914, 18.787, -69.047]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Frame.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Gear_F.geometry} material={materials.All_Material} position={[-36.366, 7.74, -70.131]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Air_tower.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Air_Fan_A.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Air_Fan_B.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Air_Fan_B_propeller.geometry} material={materials.All_Material} position={[-48.553, 67.949, -101.343]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.Air_Fan_A_propeller.geometry} material={materials.All_Material} position={[-64.065, 47.968, -64.347]} rotation={[2.843, 0.939, -1.328]} />
      <mesh geometry={nodes.CH_Air.geometry} material={materials['All_Material.001']} position={[-44.887, 47.49, -79.623]} rotation={[0, 0.395, 0]} scale={1.2} />
      <mesh geometry={nodes.Info_Tower.geometry} material={materials.All_Material} position={[0.011, 36.869, 0.001]} scale={1.5} />
      <mesh geometry={nodes.Info_Tower_Screen.geometry} material={materials.All_Material} position={[-0.006, 90.862, 0]} scale={[2, 1.5, 2]} />
      <mesh geometry={nodes.Bridge.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Earth.geometry} material={materials['All_Material.001']} position={[95.538, 32.619, -71.078]} scale={1.5} />
      <mesh geometry={nodes.Korea_Building.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Institution_Builidng.geometry} material={materials.Building_Material} />
      <mesh geometry={nodes.CH_Leaf_Body.geometry} material={materials['All_Material.001']} position={[1.41, 25.534, 113.322]} scale={2} />
      <mesh geometry={nodes.Big_Tree_House.geometry} material={materials['All_Material.001']} position={[-40.419, 20.284, 114.87]} scale={0.4} />
      <mesh geometry={nodes.Logo_Text.geometry} material={materials.Building_Material} />
      <mesh geometry={nodes.Cart01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Carbon_Land.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.House_1.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.House_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.House_3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.House_4.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.House_5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Mill.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_1.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Warehouse01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Grass1.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Grass2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Mushroom1.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Mushroom2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.MushroomLarge.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock1.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock4.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock6.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_4.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_6.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_02.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Grass_free_01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Grass_free_02.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Shrub_A.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_1.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_AA.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_BB.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.sport_store.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.studio_video_games.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.video_games_store.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_C.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_D.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_G.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Baloon.geometry} material={materials['All_Material.001']} position={[100, 87.357, -0.004]} />
      <mesh geometry={nodes.autumn_tree_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_4.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.M_building_A.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Foreign_building_B.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Foreign_building_C.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Foreign_building_D.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_4.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_6.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_7.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.japanes_temple.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.pyramid.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.sakura_tree.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.snowman.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.sphinx.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_brown_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_brown.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_gray_blue_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_gray_blue_3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_gray_blue_5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_gray_blue.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_2.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_3.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_4.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_5.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_6.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.torii_gate.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_0.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.ResidentBuilding_01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.ResidentBuilding_02.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.ResidentBuilding_03.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.GreenMouse.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Radio_01.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Radio_02.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Props_Windmill.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.A_Building_f.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.A_Building_g.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.A_Building_h.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Convention_hall_A.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Clock_tower.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_B.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Air_tower001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Wing.geometry} material={materials.All_Material} position={[-22.986, 25.267, -69.209]} />
      <mesh geometry={nodes.Props_Windmill001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Wing001.geometry} material={materials.All_Material} position={[-13.686, 25.243, -73.197]} />
      <mesh geometry={nodes.Props_Windmill002.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Wing002.geometry} material={materials.All_Material} position={[-17.688, 33.124, -78.898]} />
      <mesh geometry={nodes.CH_Air002.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.Bush_free_003.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Stand.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Lake.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_1_001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_1_002.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_1_003.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_2_001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_2_002.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_1_004.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_004.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_005.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_2_003.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_006.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_009.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_D.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.Tree_008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_016.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_017.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_018.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.tree_s.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.CH_Water.geometry} material={materials['All_Material.001']} position={[-129.545, 35.057, 47.002]} scale={1.2} />
      <mesh geometry={nodes.CH_Water001.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.stone_large_gray_blue_007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_010.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_011.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_012.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_013.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Bush_free_014.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_7.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Tree_A.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.Tree_B.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.Tree_C.geometry} material={materials['All_Material.001']} />
      <mesh
        geometry={nodes['\u0008Mill_Wing'].geometry}
        material={materials.All_Material}
        position={[-56.953, 24.423, 95.775]}
        rotation={[1.581, 0.015, -0.611]}
      />
      <mesh geometry={nodes.Carbon_Land001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_gray_blue_008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_large_gray_blue_009.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_010.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_011.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_012.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_013.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree002.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree003.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree004.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree005.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree006.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Rock009.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_014.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.stone_small_015.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.GreenMouse001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Natures_Big_Tree007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes['Carbon_Land.001'].geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_006.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Building_D001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Stand001.geometry} material={materials['All_Material.001']} />
      <mesh geometry={nodes.autumn_tree_008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_009.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_010.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.A_Building_f001.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.A_Building_c.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_004.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_005.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_006.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_007.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_009.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_010.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_011.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_008.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_009.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_010.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_011.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.Convention_hall_B.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_012.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_013.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_014.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.autumn_tree_011.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_012.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.desert_stone_small_013.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.CH_Microscope.geometry} material={materials['All_Material.001']} position={[123.65, 27.891, 42.87]} scale={1.5} />
      <mesh geometry={nodes.TreeType_015.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.TreeType_016.geometry} material={materials.All_Material} />
      <mesh geometry={nodes.M_Stand.geometry} material={materials['All_Material.001']} position={[123.504, 5.919, 37.82]} scale={1.5} />
      <mesh geometry={nodes.cube001.geometry} material={nodes.cube001.material} position={[22.778, 88.358, 0.002]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
    </group>
  )
})

useGLTF.preload(WORLD_GLB)

WorldModelGLTF.displayName = 'WorldModelGLTF'
